required = [
    "github.com/lightstep/lightstep-tracer-common",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/lightsteppb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb/collectorpbfakes",
]

[[constraint]]
  name = "github.com/lightstep/lightstep-tracer-common"
  revision = "5c08c8156e1a492c2938fcf2cc6375921ad14abc"
  # version = "1.0.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.4.3"
